export const rolePermissions = {
  manageRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageUsersRoles: ['Administrator'],
  manageHomesRoles: ['Administrator'],
  // Keep in sync with the backend "CommitteeEditor" policy (Web/Startup.cs). Drift here means the
  // committee admin UI / held-message bell shows for a role the API rejects, or hides for one it allows.
  manageCommitteesRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  // Must match AuthorizationRoleSets.EmailSender on the server, which gates the same endpoints.
  manageEmailRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageEventsRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageBlogRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageAuditLogRoles: ['Administrator'],
  // Must match the backend "Administrator" policy on EmailSuppressionController.
  manageSuppressionsRoles: ['Administrator'],
  printDirectoryRoles: ['Administrator'],
  sendEmailAsBoard: ['Board'],
  sendEmailAsWelcomeCommittee: ['WelcomeCommittee'],
  sendEmailAsGardenClub: ['GardenClub'],
  sendEmailAsSocialCommittee: ['SocialCommittee'],
  sendEmailAsSunshineCommittee: ['SunshineCommittee'],
};
