export const rolePermissions = {
  manageRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageUsersRoles: ['Administrator'],
  manageHomesRoles: ['Administrator'],
  // Keep in sync with the backend "CommitteeEditor" policy (Web/Startup.cs). Drift here means the
  // committee admin UI / held-message bell shows for a role the API rejects, or hides for one it allows.
  manageCommitteesRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageEmailRoles: ['Administrator', 'WelcomeCommittee', 'GardenClub', 'Board', 'SocialCommittee', 'SunshineCommittee'],
  manageEventsRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageBlogRoles: [
    'Administrator',
    'WelcomeCommittee',
    'GardenClub',
    'Board',
    'SocialCommittee',
    'SunshineCommittee',
    'ArchitecturalCommittee',
    'LandscapeCommittee',
  ],
  manageAuditLogRoles: ['Administrator'],
  printDirectoryRoles: ['Administrator'],
  sendEmailAsBoard: ['Board'],
  sendEmailAsWelcomeCommittee: ['WelcomeCommittee'],
  sendEmailAsGardenClub: ['GardenClub'],
  sendEmailAsSocialCommittee: ['SocialCommittee'],
  sendEmailAsSunshineCommittee: ['SunshineCommittee'],
};
